# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-10 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resultAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('detail', models.CharField(max_length=12800)),
                ('sumery', models.CharField(max_length=1280)),
                ('Jenkinsid', models.IntegerField()),
            ],
            options={
                'db_table': 'resultAll',
            },
        ),
    ]
