# Generated by Django 2.2.2 on 2020-04-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('api', models.CharField(max_length=100)),
                ('charger', models.CharField(max_length=100)),
                ('caseName', models.CharField(max_length=200)),
                ('result', models.IntegerField()),
                ('useTime', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=1000)),
                ('all', models.CharField(max_length=128000)),
                ('only', models.IntegerField()),
            ],
            options={
                'db_table': 'CaseDetail',
            },
        ),
        migrations.CreateModel(
            name='listAPIMointor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rt', models.CharField(max_length=100)),
                ('all', models.IntegerField()),
                ('fail', models.IntegerField()),
                ('only', models.IntegerField()),
            ],
            options={
                'db_table': 'listAPIMointor',
            },
        ),
        migrations.CreateModel(
            name='performanceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('startTime', models.CharField(max_length=1280)),
                ('pageTime', models.CharField(max_length=12800)),
                ('fps', models.CharField(max_length=128000)),
                ('cpu', models.CharField(max_length=128000)),
                ('mem', models.CharField(max_length=128000)),
                ('runt', models.CharField(max_length=1280)),
                ('Jenkinsid', models.IntegerField()),
                ('model', models.CharField(max_length=60)),
                ('Appname', models.CharField(max_length=40)),
                ('CodeVersion', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'performanceData',
            },
        ),
        migrations.CreateModel(
            name='resultAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('detail', models.CharField(max_length=12800)),
                ('sumery', models.CharField(max_length=1280)),
                ('Jenkinsid', models.IntegerField()),
            ],
            options={
                'db_table': 'resultAll',
            },
        ),
        migrations.CreateModel(
            name='uiAutoRunListN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('allNum', models.IntegerField()),
                ('failNum', models.IntegerField()),
                ('rt', models.CharField(max_length=100)),
                ('Jenkinsid', models.IntegerField()),
                ('link', models.CharField(max_length=200)),
                ('appName', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=200)),
                ('device', models.CharField(max_length=100)),
                ('ut', models.CharField(max_length=100)),
                ('appVersion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'uiAutoRunListN',
            },
        ),
        migrations.CreateModel(
            name='UICaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('case', models.CharField(max_length=100)),
                ('caseName', models.CharField(max_length=200)),
                ('result', models.IntegerField()),
                ('useTime', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=1000)),
                ('all', models.CharField(max_length=128000)),
                ('pic', models.CharField(max_length=1000)),
                ('listid', models.IntegerField()),
            ],
            options={
                'db_table': 'UICaseDetail',
            },
        ),
    ]
