# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-14 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='performanceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('startTime', models.CharField(max_length=1280)),
                ('pageTime', models.CharField(max_length=12800)),
                ('fps', models.CharField(max_length=128000)),
                ('cpu', models.CharField(max_length=128000)),
                ('mem', models.CharField(max_length=128000)),
                ('Jenkinsid', models.IntegerField()),
                ('Appname', models.CharField(max_length=40)),
                ('CodeVersion', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'performanceData',
            },
        ),
    ]
