# Generated by Django 2.2.2 on 2020-04-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0002_auto_20200407_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='mockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'mockData',
            },
        ),
    ]
