# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-16 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0002_performancedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancedata',
            name='runt',
            field=models.CharField(default=0, max_length=1280),
            preserve_default=False,
        ),
    ]
