# Generated by Django 2.2.2 on 2020-04-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0003_mockdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockdata',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
