# Generated by Django 2.2.2 on 2020-04-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0004_mockdata_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='failReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'failReason',
            },
        ),
    ]
