# Generated by Django 2.2.2 on 2020-04-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0006_uicasedetail_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockdata',
            name='keyword',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
