# Generated by Django 3.0.5 on 2020-05-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0007_mockdata_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='apiCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('api', models.CharField(max_length=100)),
                ('case', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('result', models.IntegerField()),
                ('useTime', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=1000)),
                ('Jenkinsid', models.IntegerField()),
            ],
            options={
                'db_table': 'apiCases',
            },
        ),
        migrations.CreateModel(
            name='APIrunlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jenkinsid', models.IntegerField()),
                ('allNum', models.IntegerField()),
                ('failNum', models.IntegerField()),
                ('rt', models.CharField(max_length=100)),
                ('ut', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'APIrunlist',
            },
        ),
    ]
